travis:
  secure:
    BINSTAR_TOKEN: Gqds+wKt5ehAAF54sZDRGiEjBk/isvNentvknG76QWIHQv5hxcSeT/cf1ZlXUU/qeIiSFrgaPUujb9uXWUaDTcffSYPHsxLlL6RetJTlbKIDtmZsMza6gYHQyE/+qeZ3wFWwh8BXWHhzkNIl/VLYmMqvW0v5LOIgckpWJRZwxgHEWy4+pHD9rtJNjBPcUf4jIzU8GiwsoHMtSW8qKjF4zdG0NtLeKHQn8o5ndWNxDENVANxDf7jVZ7gEtRQ/qI6SM9WCeSByqedlRe11EjCelbmQPo/msvWvpm3xWNo5+blkpzHl9wUzWjMA+JOlm5w7qQmymzV1WlqDGZPgx2bPAPXfZvCLXn7yfeeApziMknV30x1eHwumhnhT4hV80+ptIGGAjrczlmqNBprUweY0+7rztux8PvF3odaQwuTI+5n/Iduq5AaO8cLoUxS9uHzu656MPYu9jJ+/pq73vtlMvprLbrXwKnOjfnRYlbflNuk5pEzS9edyoXIChdJGGNdFY0KyFyHlJE1QOCP3pP47xma/zCu3poYrYHl6K1jbDd1S/dgDtGdiI7yVnLQ1P3q7p+nvHQMwvIJPUqE/lUt/4rgzjBiE77jx2UmrGcks/1S8ioWE62QAUSiJQ21pDF9Z2muikJCrHPVTrQiDFiTSYFFtSgEzYBxGbgblOWo8Y/s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
